server:
  port: 8080
  servlet:
    context-path: /internal

spring.datasource:
  url: "jdbc:postgresql://localhost:5432/gb_shop"
  username: 'geek'
  password: 'geek'
#spring:
#  profiles:
#    active: ${SPRING_PROFILES_INCLUDE:dev}
#  config:
#    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
#  cloud:
#    config:
#      label: ${SPRING_CLOUD_CONFIG_LABEL:master}
#      username: ${SPRING_CLOUD_CONFIG_USERNAME:geek_user}
#      password: ${SPRING_CLOUD_CONFIG_PASSWORD:geek_pass}
